spring:
  application:
    name: notesapp
  data:
    mongodb:
      uri: mongodb+srv://root:Samarenter%4012@samar.eos2q4v.mongodb.net/?retryWrites=true&w=majority&appName=Samar
      database: notesdb
      auto-index-creation: true